### PR TITLE
when building a heap: form (Size()/2 -1) to 0

### PR DESCRIPTION
**Pull request by laoshufeifei**
according the wiki, assuming that indices start at 1, floor(n/2) + 1 is leave,
so we should bubble down from floor(n/2) to 1;

in code, the indices start at 0, so we should bubble down from floor(n/2) - 1 to 0;

### CODE REVIEW

**Comment by emirpasic** [comment]
@laoshufeifei thanks for your input. Would you mind showing a simple test case that shows that the current implementation leads to an invalid (according to heap) state?

**Comment by laoshufeifei** [comment]
It's not a bug, just have two more redundance bubble down;
for example:
we push (15, 20, 3, 1, 2) to a new heap, now the heap.list.Size() is 5,
           15
          /    \
        20     3
     /      \
   1         2
accroding the code, we should call bubbleDownIndex(from 3 to 0), 3 is (5/2+1)
but, index-3 and index-2 are leave node, bubble down them is unnecessary.

**Comment by emirpasic** [comment]
@laoshufeifei thank you for the elaboration. I will check that again and appreciate the optimization.

On another note, how come the root is smaller than the children in your example... I just hope that did not originate from GoDS, because it would be an even bigger issue then.

**Comment by laoshufeifei** [comment]
In my example, after push(15, 20, 3, 1, 2), heap is:
```
         15
       /   \
      20    3
    /   \
   1     2
```

accroding file "binaryheap.go", the line 58:
```
	size := heap.list.Size()/2 + 1
	for i := size; i >= 0; i-- {
		heap.bubbleDownIndex(i)
	}
	# size = 5/2 + 1 = 3
```
so we should bubbleDownIndex([3, 0])

### bubbleDownIndex(3):
1. index = 3, leftIndex = 7 > heapSize(5), bubble down finish.

### bubbleDownIndex(2):
1. index = 2, leftIndex = 5 == heapSize(5), bubble down finish.

(Because index-3 and index-2 are leaves, so I think bubble down them are unnecessary.)

### bubbleDownIndex(1):
1. index = 1, leftIndex = 3 < heapSize, smallIndex = 3, **swap(1, 3)**, now heap is:
```
         15
       /   \
      1     3
    /   \
   20    2
```
2. then, index = 3, leftIndex = 7 > heapSize(5), break, bubbleDownIndex(1) finish;

### bubbleDownIndex(0):
1. index = 0, leftIndex = 1 < heapSize(5), smallIndex = 1, **swap(0, 1)**, now heap is:
```
         1
       /   \
     15     3
    /   \
   20    2
```

2. index = 1, leftIndex = 3 < heapSize(5), smallIndex = 4, **swap(1, 4)**, now heap is:
```
         1
       /   \
      2     3
    /   \
   20    15
```

3. index = 4, leftIndex = 9 > heapSize(5), break, bubbleDownIndex(0) finish;

**Pull request merged**
