### PR TITLE
Thread-safe RedBlackTree

### PR DESCRIPTION
**Pull request by shojaeix**
Hi

As a sulotion for this issue: https://github.com/emirpasic/gods/issues/174 , I decided to contribute on this great package and make some structures thread-safe.

It's still in process, but I'll be happy to know about your opinion.

### CODE REVIEW

**Comment by emirpasic** [comment]
Thread safety is not a concern of this library and can be tackled on a higher layer, i.e. when you do reads or writes you can protect the structure with R or RW mutexes according to your needs. This will allow consumers of this library to control this explicitly in places where this is needed. This is also trivial, so I am a bit split in opinion if this is needed at the moment, or otherwise, we would have to do the same for all the other data structures and live with the performance hit thereof.

**Comment by shindanai-midas** [comment]
@emirpasic I found this problem also. How can I implement Put, Remove with Thread-Safe at Higher level? I have tried to create a struct which has mutex and *rbt.Tree but Race detector still tell me Add Method has race condition. Please help

Here my struct
```
type OrderList struct {
	name       string
	mu         *sync.Mutex
	list       *rbt.Tree // List based on Red Black Tree
	latestSize int64
}
```

And my method
```
func (l *OrderList) Remove(ord *order.Order) {
	l.mu.Lock()
	l.list.Remove(ord)
	l.mu.Unlock()
}
```

**Comment by emirpasic** [comment]
@shindanai-midas Something like that, I would suggest putting the unlock mechanism into a defer function as Golang suggests. For your error, you are putting the mutex within the Remove function and the error is about the Add function, so something does not make sense here or you need to provide how your Add function looks like?

**Comment by shindanai-midas** [comment]
@emirpasic Thank you, now my code is working fine. Data races happened in other line of code which using this method and I fixed that. Sorry for confusing.

**Pull request closed without merging**
